version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    container_name: zapcore_postgres
    environment:
      POSTGRES_DB: zapcore
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_INITDB_ARGS: "--encoding=UTF-8 --lc-collate=C --lc-ctype=C"
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./internal/infra/database/migrations:/docker-entrypoint-initdb.d
    networks:
      - zapcore_network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d zapcore"]
      interval: 10s
      timeout: 5s
      retries: 5

  redis:
    image: redis:7-alpine
    container_name: zapcore_redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - zapcore_network
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

  minio:
    image: minio/minio:RELEASE.2025-03-12T18-04-18Z-cpuv1
    container_name: zapcore_minio
    command: server /data --console-address ":9001"
    environment:
      MINIO_ROOT_USER: admin
      MINIO_ROOT_PASSWORD: 4xN4PEDyxijbN4gM
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - minio_data:/data
    networks:
      - zapcore_network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 30s
      timeout: 20s
      retries: 3

# Aplicação rodará localmente
  # zapcore:
  #   build:
  #     context: .
  #     dockerfile: Dockerfile
  #   container_name: zapcore_app
  #   environment:
  #     - DB_HOST=postgres
  #     - DB_PORT=5432
  #     - DB_NAME=postgres
  #     - DB_USER=zapcore
  #     - DB_PASSWORD=postgres
  #     - DB_SSLMODE=disable
  #     - REDIS_HOST=redis
  #     - REDIS_PORT=6379
  #     - PORT=8080
  #     - HOST=0.0.0.0
  #     - LOG_LEVEL=info
  #     - API_KEY=zapcore-api-key-development-only
  #     - JWT_SECRET=your-super-secret-jwt-key-change-in-production
  #     - ENV=development
  #     - WHATSAPP_WEBHOOK_URL=http://localhost:8080/webhook
  #     - WHATSAPP_MEDIA_PATH=./uploads
  #     - WHATSAPP_SESSION_PATH=./sessions
  #   ports:
  #     - "8080:8080"
  #   depends_on:
  #     postgres:
  #       condition: service_healthy
  #     redis:
  #       condition: service_healthy
  #   networks:
  #     - zapcore_network
  #   volumes:
  #     - ./logs:/app/logs
  #     - ./uploads:/app/uploads
  #   restart: unless-stopped

volumes:
  postgres_data:
  redis_data:
  minio_data:

networks:
  zapcore_network:
    driver: bridge
